export interface FfxivSpecialChar {
  char: string;
  label: string;
  category: string;
}

export const FFXIV_SPECIAL_CHARS: FfxivSpecialChar[] = [
  { char: '\uE020', label: 'IME: Hiragana', category: 'IME' },
  { char: '\uE021', label: 'IME: Katakana', category: 'IME' },
  { char: '\uE022', label: 'IME: Full-width English', category: 'IME' },
  { char: '\uE023', label: 'IME: Half-width Katakana', category: 'IME' },
  { char: '\uE024', label: 'IME: Half-width English', category: 'IME' },
  { char: '\uE025', label: 'IME: Hangul', category: 'IME' },
  { char: '\uE026', label: 'IME: Chinese', category: 'IME' },
  { char: '\uE033', label: 'Item Level', category: 'UI' },
  { char: '\uE034', label: 'Garden Patch Marker', category: 'UI' },
  { char: '\uE035', label: 'Housing Item Marker', category: 'UI' },
  { char: '\uE037', label: 'Knowledge Level (Occult Crescent)', category: 'UI' },
  { char: '\uE038', label: 'Resistance Rank (Save the Queen)', category: 'UI' },
  { char: '\uE039', label: 'Variable Attribute Indicator', category: 'UI' },
  { char: '\uE03A', label: 'Elemental Level (Eureka)', category: 'UI' },
  { char: '\uE03B', label: 'Glamour Indicator', category: 'UI' },
  { char: '\uE03C', label: 'High Quality (HQ)', category: 'UI' },
  { char: '\uE03D', label: 'Collectable', category: 'UI' },
  { char: '\uE03E', label: 'Dice (/dice)', category: 'UI' },
  { char: '\uE040', label: 'Auto-Translate Start', category: 'UI' },
  { char: '\uE041', label: 'Auto-Translate End', category: 'UI' },
  { char: '\uE042', label: 'Sign: Attack', category: 'Sign' },
  { char: '\uE043', label: 'Sign: Ignore', category: 'Sign' },
  { char: '\uE044', label: 'Sign: Bind', category: 'Sign' },
  { char: '\uE048', label: 'Crystals Tab', category: 'UI' },
  { char: '\uE049', label: 'Gil', category: 'UI' },
  { char: '\uE04A', label: 'Sign: Circle', category: 'Sign' },
  { char: '\uE04B', label: 'Sign: Square', category: 'Sign' },
  { char: '\uE04D', label: 'Sign: Triangle', category: 'Sign' },
  { char: '\uE04E', label: 'Sign: Plus', category: 'Sign' },
  { char: '\uE051', label: 'Mouse: Left Click', category: 'Mouse' },
  { char: '\uE052', label: 'Mouse: Right Click', category: 'Mouse' },
  { char: '\uE053', label: 'Mouse: Both Buttons', category: 'Mouse' },
  { char: '\uE054', label: 'Mouse: Scroll Wheel', category: 'Mouse' },
  { char: '\uE057', label: 'Mouse: Button 3', category: 'Mouse' },
  { char: '\uE058', label: 'Mouse: Button 4', category: 'Mouse' },
  { char: '\uE059', label: 'Mouse: Button 5', category: 'Mouse' },
  { char: '\uE05B', label: 'Debuff (Combat Log)', category: 'Battle' },
  { char: '\uE05C', label: 'Buff (Combat Log)', category: 'Battle' },
  { char: '\uE05D', label: 'Cross-World Player', category: 'UI' },
  { char: '\uE060', label: 'Party: Role 1', category: 'Party' },
  { char: '\uE061', label: 'Party: Role 2', category: 'Party' },
  { char: '\uE062', label: 'Party: Role 3', category: 'Party' },
  { char: '\uE063', label: 'Party: Role 4', category: 'Party' },
  { char: '\uE064', label: 'Party: Role 5', category: 'Party' },
  { char: '\uE065', label: 'Party: Role 6', category: 'Party' },
  { char: '\uE066', label: 'Party: Role 7', category: 'Party' },
  { char: '\uE067', label: 'Party: Role 8', category: 'Party' },
  { char: '\uE068', label: 'Party: Role 9', category: 'Party' },
  { char: '\uE069', label: 'Party: Role 10', category: 'Party' },
  { char: '\uE06D', label: 'Time: AM', category: 'Time' },
  { char: '\uE06E', label: 'Time: PM', category: 'Time' },
  { char: '\uE06F', label: 'Combat Log Detail', category: 'Battle' },
  { char: '\uE071', label: 'Enemy ID: A', category: 'Enemy' },
  { char: '\uE072', label: 'Enemy ID: B', category: 'Enemy' },
  { char: '\uE073', label: 'Enemy ID: C', category: 'Enemy' },
  { char: '\uE074', label: 'Enemy ID: D', category: 'Enemy' },
  { char: '\uE075', label: 'Enemy ID: E', category: 'Enemy' },
  { char: '\uE076', label: 'Enemy ID: F', category: 'Enemy' },
  { char: '\uE077', label: 'Enemy ID: G', category: 'Enemy' },
  { char: '\uE078', label: 'Enemy ID: H', category: 'Enemy' },
  { char: '\uE079', label: 'Enemy ID: I', category: 'Enemy' },
  { char: '\uE07A', label: 'Enemy ID: J', category: 'Enemy' },
  { char: '\uE07B', label: 'Enemy ID: K', category: 'Enemy' },
  { char: '\uE07C', label: 'Enemy ID: L', category: 'Enemy' },
  { char: '\uE07D', label: 'Enemy ID: M', category: 'Enemy' },
  { char: '\uE07E', label: 'Enemy ID: N', category: 'Enemy' },
  { char: '\uE07F', label: 'Enemy ID: O', category: 'Enemy' },
  { char: '\uE080', label: 'Enemy ID: P', category: 'Enemy' },
  { char: '\uE090', label: 'Party Number: 1', category: 'Party' },
  { char: '\uE091', label: 'Party Number: 2', category: 'Party' },
  { char: '\uE092', label: 'Party Number: 3', category: 'Party' },
  { char: '\uE093', label: 'Party Number: 4', category: 'Party' },
  { char: '\uE094', label: 'Party Number: 5', category: 'Party' },
  { char: '\uE095', label: 'Party Number: 6', category: 'Party' },
  { char: '\uE096', label: 'Party Number: 7', category: 'Party' },
  { char: '\uE097', label: 'Party Number: 8', category: 'Party' },
  { char: '\uE0B1', label: 'Instance Area: 1', category: 'Instance' },
  { char: '\uE0B2', label: 'Instance Area: 2', category: 'Instance' },
  { char: '\uE0B3', label: 'Instance Area: 3', category: 'Instance' },
  { char: '\uE0B4', label: 'Instance Area: 4', category: 'Instance' },
  { char: '\uE0B5', label: 'Instance Area: 5', category: 'Instance' },
  { char: '\uE0B6', label: 'Instance Area: 6', category: 'Instance' },
  { char: '\uE0BB', label: 'Clickable Link Indicator', category: 'UI' },
  { char: '\uE0BC', label: 'Level Sync', category: 'UI' },
  { char: '\uE0BD', label: 'Quest Sync', category: 'UI' },
  { char: '\uE0BE', label: 'Level Adjust Quest', category: 'UI' },
  { char: '\uE0BF', label: 'Job-locked Quest', category: 'UI' },
  { char: '\uE0C1', label: 'Enemy Rank: I', category: 'Enemy' },
  { char: '\uE0C2', label: 'Enemy Rank: II', category: 'Enemy' },
  { char: '\uE0C3', label: 'Enemy Rank: III', category: 'Enemy' },
  { char: '\uE0C4', label: 'Enemy Rank: IV', category: 'Enemy' },
  { char: '\uE0C5', label: 'Enemy Rank: V', category: 'Enemy' },
  { char: '\uE0D0', label: 'Local Time', category: 'Time' },
  { char: '\uE0D1', label: 'Server Time', category: 'Time' },
  { char: '\uE0D2', label: 'Eorzea Time', category: 'Time' },
  { char: '\uE0D3', label: 'Local Time (DE)', category: 'Time' },
  { char: '\uE0D4', label: 'Server Time (DE)', category: 'Time' },
  { char: '\uE0D5', label: 'Eorzea Time (DE)', category: 'Time' },
  { char: '\uE0D6', label: 'Local Time (FR)', category: 'Time' },
  { char: '\uE0D7', label: 'Server Time (FR)', category: 'Time' },
  { char: '\uE0D8', label: 'Eorzea Time (FR)', category: 'Time' },
  { char: '\uE0E1', label: 'Party Number: Self (1)', category: 'Party' },
  { char: '\uE0E2', label: 'Party Number: Self (2)', category: 'Party' },
  { char: '\uE0E3', label: 'Party Number: Self (3)', category: 'Party' },
  { char: '\uE0E4', label: 'Party Number: Self (4)', category: 'Party' },
  { char: '\uE0E5', label: 'Party Number: Self (5)', category: 'Party' },
  { char: '\uE0E6', label: 'Party Number: Self (6)', category: 'Party' },
  { char: '\uE0E7', label: 'Party Number: Self (7)', category: 'Party' },
  { char: '\uE0E8', label: 'Party Number: Self (8)', category: 'Party' },
];

export const FFXIV_CHAR_CATEGORIES = [
  'All',
  'UI',
  'Sign',
  'Party',
  'Battle',
  'Mouse',
  'IME',
  'Time',
  'Instance',
  'Enemy',
] as const;
